### PR TITLE
add support for udp interface

### PR DESCRIPTION
**Pull request by Rezenders**
Add support for udp connection. As discussed in Issue #78

### CODE REVIEW

**Comment by AlexisFetet** [comment]
Could you please update the readme with the new parameters, and specify that device and baudrate are only used in serial connection (and same with udp_port and udp_address are used in udp connection only). Other than that it looks good to me.

**Comment by AlexisFetet** [comment]
Also maybe change the default `udp_address` to `0.0.0.0` and use `12345` as `udp_port` default value (as in [here](https://github.com/bluerobotics/ping-python/blob/78e0299f3bec1ef3feb8e35f5e1c93b21428d317/brping/device.py#L64)), what do you think about that?

**Comment by Rezenders** [comment]
Done

**Comment by AlexisFetet** [comment]
Thanks a lot for your help.

**Pull request merged**
